### ISSUE TITLE
Fails on Java 11 due to old JRuby version

### ISSUE THREAD

**Issue by kornysietsma** [DomKM/optimus-sass#4]
On Java 11 I get an error
```
...
Caused by: java.lang.RuntimeException: unsupported Java version: 11
	at org.jruby.RubyInstanceConfig.initGlobalJavaVersion(RubyInstanceConfig.java:1878)
	at org.jruby.RubyInstanceConfig.<clinit>(RubyInstanceConfig.java:1585)
	... 76 more
```
This is presumably because optimus-sass depends on JRuby 1.7.11 which dates back to 2014 - Java 11 support is in JRuby 9.2.1.0 and later.

**Comment by domkm** [comment]
I'm not actively using this library and haven't for quite some time but I am open to a PR to address this issue.

**Comment by paradoja** [comment]
I created a PR that addresses this in #5 .
